config/routes.rb
Rails.application.routes.draw do
 
	#Routes para match
	resources :matches do
  		member do
    		get 'add_match', 'play'
  		end
	end
	

	#routes for devise for players   
	devise_for :players

	devise_scope :player do
		#Si el usuario inicio sesion
  		authenticated :player do
    		root :to => 'matches#front', as: :authenticated_root
  		end
  		#Si el usuario no inicio sesion
	  	unauthenticated :player do
	    	root :to => 'devise/sessions#new', as: :unauthenticated_root
	  	end
	end


	#routes for numbers
	resources :numbers 
	get 'numbers/new'
	post 'numbers/create'
	post 'numbers/new_play_number'
end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :user_matches
	has_many :numbers
end

app/models/number.rb
class Number < ActiveRecord::Base
	
	before_create :validation_input

	after_create :validation_equals, :validation_regular

		
	

	belongs_to :match
	belongs_to :player


	



	def validation_input
		#validamos si el numero tiene digitos distintos.
		@array_elements = ["0","1","2","3","4","5","6","7","8","9"]
		#.split convierte un string en un array
		@number = self.number.split(//)
		@array_elements.each do |i|	
			@count = 0
			@number.each do |e|
				if i == e then
					@count += 1
					if @count > 1 then
						return false
					end
				end
			end
		end
	end

	def validation_equals
		#comparar el numero que ingreso contra el numero a adivinar y ver cuantos mal, regular y bien hay
		nro1 = "1234".split("")
		nro2 = "0734".split("")
		cant = nro1.size
		equals = 0
		i = 0
		while i < cant
			if nro1[i] == nro2[i] then
				equals += 1
			end
			i += 1
		end  
		return equals
	end


	def validation_regular
		#comparar el numero que ingreso contra el numero a adivinar y ver cuantos mal, regular y bien hay
		nro1 = "9134"
		nro2 = "1234"

		cont1 = 0
		cont2 = 0
		regular = 0

		nro1.split("").each do |n1|
			cont1 += 1	
			cont2 = 0
			nro2.split("").each do |n2|
				cont2 += 1
				if n1 == n2 then
					if cont1 == cont2 then
						puts "nro1: "+n1.to_s
						puts "nro1: "+n2.to_s
						regular += 1
					end
				end
			end
		end 
		return regular
	end
end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :numbers
  has_many :user_matches
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_match.rb
class UserMatch < ActiveRecord::Base
	belongs_to :user
	belongs_to :match
	belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	def index
		@matches = UserMatch.joins(:match).where("vs_player = ? and available = ? and player_id != ?", true, true, current_player.id)
	end

	def new
		@match = Match.new
	end

	def create
		new_match = Match.create(
				:name => params[:match][:name],
			  	:vs_machine => params[:match][:vs_machine],
			  	:vs_player => params[:match][:vs_player],
			  	:available => true)

		UserMatch.create(
				:player_id => current_player.id,
				:match_id => new_match.id)
		
		#Number.create (
		#		:player_id => current_player.id,
		#		:number => current_player.id,
		#		:match_id => new_match.id,
		#		:player_number => true
		#		)



		#cuando voy al new de numbers envio el numero de partida
		redirect_to "/numbers/new?match=#{new_match.id}&lenght=#{params[:lenght]}"
	end


	def show
		@user_match = UserMatch.where("match_id = ?", params[:id]).first
	end


	def add_match
		match = Match.find(params[:id])
		match.available = false
		match.save

		UserMatch.create(
				:player_id => current_player.id,
				:match_id => params[:id])

		redirect_to "/numbers/new?match=#{params[:id]}"
	end

	def play

		@num_current_user = Number.where("match_id = ? and player_number = ? and player_id = ?", params[:id], true, current_player.id).first.number
		@current_match = params[:id]
	end

end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
	#before_filter :find_model
	
	def index
		@numbers = current_player.numbers
		@email = current_player.email
	end

	def new
		match_id = params[:match] 
		@match = Match.find(match_id)

		@number = current_player.numbers.build

		@max_length = params[:lenght]
	end

	def show 
		@number = Number.find(params[:id])
	end

	def create	
		if params[:number][:player_number] == "true" then #Esto va para que identifique si es el numero principal de la partida
			new_number = Number.new(:number => params[:number][:number], 
									:match_id => params[:number][:match_id].to_i, 
									:player_id => current_player.id, 
									:player_number => true)
		end
		if new_number.save then

			#estas validaciones son para enviar a play y ver los resultados
			@equals = new_number.validation_equals
			@regulars = new_number.validation_regular

			redirect_to "/matches/#{new_number.match_id}/play"
		else
			flash[:notice] = "Ocurrio un error al grabar los datos"
			redirect_to "/numbers/new"
		end
	end





	def new_play_number
		new_number = Number.new(:number => params[:number], 
					:match_id => params[:match].to_i, 
					:player_id => current_player.id, 
					:player_number => false)
		if new_number.save then
			render :status => 100
		else
			render :status => 401
		end      
	end




end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_filter :find_model

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kramo</title>
  <!--Tipografias de Kramo-->
  <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>

    <!--Estilos de Kramo-->
  <link rel="stylesheet" href="main.css">



  <script src="https://www.gstatic.com/firebasejs/3.0.5/firebase.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.0.5/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.0.5/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.0.5/firebase-database.js"></script>


  	<script src="https://www.gstatic.com/firebasejs/live/3.0/firebase-app.js"></script>
	<script src="https://www.gstatic.com/firebasejs/live/3.0/firebase-auth.js"></script>
	<script src="https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.js"></script>
	<link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.css" />





	 https://project-7484915963980617408.firebaseapp.com/__/auth/handler |


  <script>
    // Initialize Firebase
    // TODO: Replace with your project's customized code snippet
    var config = {
      apiKey: "25eac70560382dd7a8cffd489096a8d6335b0bed",
      authDomain: "project-7484915963980617408.firebaseapp.com",
      databaseURL: "https://project-7484915963980617408.firebaseio.com/"
      //storageBucket: "bucket.appspot.com",
    };

    firebase.initializeApp(config);
  </script>




  









  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<!---<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>-->


</body>
</html>

app/views/matches/index.html.erb
<!DOCTYPE>

<html>

    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="main.css">
    </head>
    <body>
        <div class="container-fluid">
            <div class ="row">
                <ul>
                <li id="color-1" class="col-md-12">UNETE A UNA PARTIDA</li>
						<% @matches.each do |m| %>
							<li id="color-2" class="col-md-12">
							<a href="/matches/<%=m.match_id%>" style="color:white">
							<%= m.match.name %> - <%= m.player.email %> <a href="matches/<%= m.match_id %>/add_match">Juega ahora</a>
							</a>
						<% end %>
					</li>
                <li id="color-0" class="col-md-12">
					<a href="/">Volver</a>
				</li>


	</body>
</html>

app/views/matches/new.html.erb
<!DOCTYPE>

<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="main.css">
    </head>
    <body>
        <div class="container-fluid">
            <div class ="row">
            <%= form_for(@match) do |n| %>
                <ul>
                    <li id="color-1" class="col-md-12">
                    	<div>
							<%= n.text_field :name, placeholder:"NOMBRE DE LA PARTIDA" %>
						</div>
                    </li>


                    <li id="color-1" class="col-md-12">
                        <div>
                            <input type="text" placeholder="Cantidad números" id="lenght" name="lenght" />
                        </div>
                    </li>


                    <li id="color-2" class="col-md-6">
                    	<div>
							<%= n.check_box :vs_machine%>
							<label>
								MACHINE
							</label>
						</div>
                    </li>

                    <li id="color-3" class="col-md-6">
                    	<div>
							<%= n.check_box :vs_player%>
							<label>
								PLAYER
							</label>
						</div>
                    </li>

                    <li id="color-4" class="col-md-12">
                    	<%= n.submit "Nueva partida" %>
						<%end%>
                    </li>

                    <li id="color-5" class="col-md-12">
						<a href="/">Volver</a>
                    </li>
                    <li id="color-0" class ="col-md-12"></li>
                    <li id="color-0" class ="col-md-12"></li>
               </ul>
          </div>
    </body>
</html> 

		
		

		

		
		

app/views/matches/play.html.erb
<!DOCTYPE html>
<html>
	<script>
		function isNumberKey(evt){
		    var charCode = (evt.which) ? evt.which : event.keyCode
		    if (charCode > 31 && (charCode < 48 || charCode > 57))
		        return false;
		    return true;
		}

        function updateNumbers() {
            var number = document.getElementById("input_number").value;
            var match = <%= @current_match %>

			var json_text = '{"number":"'+number+'" , "match":"'+match+'"}';
			var json_data = JSON.parse(json_text);

			url = "/numbers/new_play_number"

			console.log(json_data)
			

            $.ajax({
                    type: "POST",
                    url: url,
                    data: json_data,
                    dataType: 'json',
                    success: function() {
                        //hacer un query y mostrar actualizar el listado de numbers y actvar el boton correspondiente
                    },
                    error: function() {
                        //volver a pedir el numer
                    }
               });

        }
        </script>
	<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="main.css">
    </head>
    <body>
        <div class="container-fluid">
            <div class ="row">
                <ul>
					<li id="color-1" class="col-md-12">PARTIDA CONTRA HAGNR</li>
					<li id="color-2" class="col-md-12">MI NUMERO: <%= @num_current_user.to_s %></li>
					<li id="color-3" class="col-md-12">
					<!-- max lenght deberia llevar una variable modificable cuando creamos la partida o elegimos un modo de juego -->
						<input type="text", maxlength="4", placeholder= "ELIJE UN NUMERO", name="input_nuplaceholder: "ELIJA UN NUMERO"mber" id="input_number" onkeypress="return isNumberKey(event)"></input>
					</li>
					<li id="color-4" class="col-md-12">
						<a href="#">
				            <div onclick="updateNumbers()">    
				                <p>Pregutar</p>
				            </div>
				        </a>
				    </li>
				    <li id="color-0-bis" class="col-md-12"></li>
	
	</body>
</html>

app/views/matches/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
   		<link rel="stylesheet" href="css/bootstrap.min.css">
    	<link rel="stylesheet" href="main.css">
		<title>Kramo</title>
	</head>
	<body>

		<div id="color-1" class="col-md-12">Name: <%= @user_match.match.name %></div>
		<div id="color-2" class="col-md-12">Creator: <%= @user_match.player.email%></div>

		<a href="/matches/<%= @user_match.match.id %>/add_match">¡ Juega Ahora !</a>

	</body>
</html>

app/views/numbers/index.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="kramo.css">
<title>Kramo</title>
</head>
<body>
<% if player_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_player_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_player_session_path)  %>  
  </li>
<% end %>
<%= @email %>
<% @numbers.each do |n| %>
	<div class = "number-box" > <%= n.number %> </div>
	<div class = "number-box-mail" > <%= n.player.email %> </div>
<% end %>
<a href="/">Volver</a>
</body>

app/views/numbers/new.html.erb
<!DOCTYPE html>
<html>
	<head>

		<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="css/bootstrap.min.css">
   		<link rel="stylesheet" href="main.css">
		
		<title>Kramo</title>
	</head>
	<body>
		 <div class="container-fluid">
		 <div class="row">
		 	<ul>
	     		<li id="color-1" class="col-md-12">COMIENCE A JUGAR</li>
<<<<<<< HEAD
	     		
	     		<%= form_for(@number) do |n| %>
		     		<li id="color-2" class="col-md-12">
						<%= n.hidden_field :match_id, :value => @match.id %>
						<%= n.hidden_field :player_number, :value => "true" %>
						<%= n.text_field :number, placeholder: "ELIJA UN NUMERO", maxlength:"#{@max_length}" %>	
					</li>
					
					<li id="color-3" class="col-md-12">
		     			<%= n.submit "Siguiente" %>
	     			</li>
				<%end%>
				
=======
	     		<li id="color-2" class="col-md-12">
		     		<%= form_for(@number) do |n| %>
					<%= n.hidden_field :match_id, :value => @match.id %>
					<%= n.hidden_field :player_number, :value => "true" %>
					<%= n.text_field :number, maxlength:"4", placeholder: "ELIJA UN NUMERO"%>	
				</li>
				<li id="color-3" class="col-md-12">
		     		<%= n.submit "Siguiente" %>
					<%end%>
				</li>
>>>>>>> 5cd2c54f5b32c889bf661f4fcfe4ce695007ecb6
				<li id="color-4" class="col-md-12"></li>
				<li id="color-4" class="col-md-12"></li>
				<li id="color-4" class="col-md-12"></li>
	     	
	     	</ul>

		</div>
		</div>
	</body>
</html>

app/views/numbers/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="kramo.css">
		<link href='https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise' rel='stylesheet' type='text/css'>
		<title>Kramo</title>
	</head>
	<body>
		<h1> Número </h1>
		<h2> <%= @number.number %> </h2>
	</body>
</html>